import Head from 'next/head';
import { Montserrat, Work_Sans } from 'next/font/google';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import MouseLight from '@/components/MouseLight';

import '@/styles/globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--montserrat-font',
});
const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--workSans-font',
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Create global variable to use it in css */}
      <style jsx global>{`
        :root {
          --montserrat-font: ${montserrat.style.fontFamily};
          --workSans-font: ${workSans.style.fontFamily};
        }
      `}</style>

      <Header />
      <Component {...pageProps} />
      {/* <MouseLight /> */}
      <Footer />
    </>
  );
}
